# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7615b90cde732e664101f3a4fc489635c763072e03afc74316b9b955e56e65c443741ec2430f750d24be7d323c21620555d2886eada9706409cc5678b3f148a7

test:
  secret_key_base: 1a0f617bd604d507cf64437f1172e96c825581b5d53b0fb0bf294a6d3776296905a8299818e5f9e126aba8d24c9357d3a626fabeed891cecf685440a81a6d542

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
